CREATE TABLE EVENTOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombreEvento VARCHAR(255) NOT NULL,
    descripcion TEXT,
    fecha DATE NOT NULL,
    hora VARCHAR(5) NOT NULL,
    lugar VARCHAR(255) NOT NULL,
    edadMinima INT NOT NULL,
    edadMaxima INT NOT NULL,
    imagen LONGBLOB NOT NULL
);

CREATE TABLE INSCRIPCIONES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    correo VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    eventoID INT NOT NULL,
    FOREIGN KEY (eventoID) REFERENCES EVENTOS(id) ON DELETE CASCADE
);

CREATE TABLE USUARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    correo VARCHAR(255) UNIQUE NOT NULL,
    contrasena VARCHAR(255) NOT NULL
);

INSERT INTO USUARIOS (correo, contrasena) 
VALUES ('noreplymisionerosespiritusanto@gmail.com', 'admin123');
